<?php
/**
 * @file
 * Defines a formatter for the taxon formatters module that can display NBN WMS
 * maps overlaid onto OpenLayers maps.
 */

/**
 * Implements hook_taxon_formatter_types().
 */
function nbn_dynamic_map_taxon_formatter_types() {
  $formatter = array(
    'nbn_dynamic_map' => array(
      'title' => t('NBN Dynamic Map'),
      // Field type is tvk, tlick or brc (+GBIF?).
      'field_type' => 'tvk',
      // Function that generates the form using Forms API, with arguments for
      // the current settings values, type name (e.g. nbn_dynamic_map) and
      // optional $args.
      'form_callback' => 'nbn_dynamic_map_taxon_formatter_settings_form',
      // Can be used to pass arguments to the form.
      'form_args' => array(),
    ),
  );
  return $formatter;
}

/**
 * This defines the drupal form used for the settings of this formatter type.
 */
function nbn_dynamic_map_taxon_formatter_settings_form($settings, $type, $args) {
  if ($type == 'nbn_dynamic_map') {
    // Apply some defaults.
    $settings = array_merge(array(
      'width' => 200,
      'height' => 300,
    ), $settings);
    $form = array();
    // @todo validate width and height.
    $form['width'] = array(
      '#type' => 'textfield',
      '#title' => t('Width (px)'),
      '#description' => t('Width of the map in pixels.'),
      '#required' => TRUE,
      '#default_value' => $settings['width'],
    );
    $form['height'] = array(
      '#type' => 'textfield',
      '#title' => t('Height (px)'),
      '#description' => t('Height of the map in pixels.'),
      '#required' => TRUE,
      '#default_value' => $settings['height'],
    );
    $form['datasets'] = array(
      '#type' => 'textarea',
      '#title' => t('Datasets'),
      '#description' => t('List the keys of the datasets to restrict the query to one per line, or leave blank for no dataset filter.'),
      '#required' => FALSE,
      '#default_value' => $settings['datasets'],
      '#wysiwyg' => FALSE,
    );
    $form['colour'] = array(
      '#type' => 'textfield',
      '#title' => t('Colour (rrggbb)'),
      '#description' => t('Colour of the grid squares in hexadecimal RGB format.'),
      '#default_value' => empty($settings['colour']) ? 'df4a21' : $settings['colour'],
    );
    $form['opacity'] = array(
      '#type' => 'textfield',
      '#title' => t('Opacity (%)'),
      '#description' => t('Opacity of the grid squares from 0 (transparent) to 100 (opaque).'),
      '#default_value' => empty($settings['opacity']) ? '80' : $settings['opacity'],
    );
  }
  return $form;
}

/**
 * Implements the output theme function.
 */
function theme_nbn_dynamic_map_taxon_formatter_output($params) {
  $item = $params['item'];
  $preset = $params['preset'];
  // Return nothing if no TVK.
  $tvk = trim($item['value']);
  if (empty($tvk)) {
    return '';
  }
  
  // Create an Indicia map panel which uses OpenLayers.
  iform_load_helpers(array('map_helper'));
  $map = map_helper::map_panel(array(
    'presetLayers' => array('google_satellite', 'google_physical', 'osm'),
    'editLayer' => FALSE,
    'initial_lat' => variable_get('indicia_map_centroid_lat', 55),
    'initial_long' => variable_get('indicia_map_centroid_long', -1),
    'initial_zoom' => variable_get('indicia_map_zoom', 5),
    'width' => $preset['settings']['width'],
    'height' => $preset['settings']['height'],
    'standardControls' => array('layerSwitcher', 'panZoomBar'),
    'rememberPos' => FALSE,
  ), array('theme' => map_helper::$js_path . 'theme/default/style.css'));
  
  // Prepare settings for the NBN Atlas WMS request.
  if (!empty($preset['settings']['datasets'])) {
    $ds = str_replace("\r\n", "\n", $preset['settings']['datasets']);
    $ds = str_replace("\r", "\n", $ds);
    $ds = explode("\n", trim($ds));
    $datasets = 'data_resource_uid:' . implode(' OR data_resource_uid:', $ds);
  }
  else {
    $datasets = '';
  }
  $colour = empty($preset['settings']['colour']) ? 'df4a21' : $preset['settings']['colour'];
  $opacity = empty($preset['settings']['opacity']) ? '0.8' : $preset['settings']['opacity'] / 100;
    
  // q and fq get embedded straight in the URL rather than passed as a 
  // property, as OpenLayers capitalises to Q and FQ. The Atlas ignores FQ.
  map_helper::$javascript .= '
mapSettingsHooks.push(function(opts) {
  var nbn = new OpenLayers.Layer.WMS(
    "NBN Atlas data", 
    "https://records-ws.nbnatlas.org/ogc/wms/reflect" + 
      "?q=lsid:' . $tvk . '" +
      "&fq=' . $datasets . '", 
    {
      LAYERS: "ALA:occurrences", 
      CRS:"EPSG:3857", 
      FORMAT:"image/png", 
      TRANSPARENT: true,
      ENV: "colourmode:osgrid;gridlabels:true;gridres:singlegrid;opacity:1;color:' . $colour . ';"
    },
    {
      isBaseLayer: false,
      opacity: ' . $opacity .',
    }
  );  

  opts.layers.splice(0, 0, nbn);
});
';
  $args = array(
    'map' => $map,
    'preset' => $preset);
  $r = theme('nbn_dynamic_map_output', $args);
  handle_resources();
  return $r;
}

/**
 * Theme function to wrap the dynamic map output in NBN terms and conditions.
 */
function theme_nbn_dynamic_map_output($args) {
  $result = '<div style="width: ' . $args['preset']['settings']['width'] . 'px; margin: 0 auto;">';
  $result .= $args['map'];
  $result .= '<table width="100%">' .
      '<tbody><tr><td align="left"><a href="https://nbnatlas.org/help/nbn-atlas-terms-use/">' .
      t('NBN Atlas Terms of Use') . '</a></td><td align="right"><a href="https://nbnatlas.org">' .
      '<img src="https://easymap.nbnatlas.org/NBNPower.gif" alt="NBN Logo" width="100" height="14"></a></td></tr></tbody></table></div>';
  return $result;
}

/**
 * Implements of hook_theme().
 */
function nbn_dynamic_map_theme() {
  $theme = array();
  $theme["nbn_dynamic_map_taxon_formatter_output"] = array(
    'arguments' => array('element' => NULL),
  );
  $theme["nbn_dynamic_map_output"] = array(
    'arguments' => array('element' => NULL),
  );
  return $theme;
}
